import setuptools

setuptools.setup(
    name="splice_ninja",
    version="0.1",
    include_package_data=True,
    packages=setuptools.find_packages(),
    install_requires=[
        "numpy",
        "pandas",
        "argparse",
        "wandb",
        "h5py",
        "tqdm",
        "scipy",
        "statsmodels",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "torch",
        "lightning",
        "pyfaidx",
        "genomepy",
        "biopython",
        "joblib",
        "einsum",
        "rotary-embedding-torch",
    ],
)
